### PR TITLE
fix: bump cdkVersion to 2.224.0 to fix Go bindings compilation

### PR DESCRIPTION
**Pull request by aemada-aws**
## Problem

`awscdk-kubectl-go` does not compile with `aws-cdk-lib >= v2.224.0`:

```
duplicate method Env
undefined: awscdk.ResourceEnvironment
```

Reported in [aws/aws-cdk#37405](https://github.com/aws/aws-cdk/issues/37405).

## Root Cause

In [aws-cdk#35971](https://github.com/aws/aws-cdk/pull/35971) (shipped in v2.224.0), reference interfaces including `ResourceEnvironment` were moved from `aws-cdk-lib` to `aws-cdk-lib/interfaces` to resolve cyclic dependencies between service modules (see [aws/aws-cdk#36060](https://github.com/aws/aws-cdk/issues/36060)).

Since this package compiled against `aws-cdk-lib@2.94.0`, jsii-pacmak generated Go code referencing `awscdk.ResourceEnvironment` (old location). When users depend on `awscdk/v2 >= v2.224.0`, the embedded `awslambda.LayerVersion` interface declares `Env() *interfaces.ResourceEnvironment`, conflicting with the generated `Env() *awscdk.ResourceEnvironment`.

## Fix

Bump `cdkVersion` from `2.94.0` to `2.224.0` so jsii-pacmak generates Go bindings using `interfaces.ResourceEnvironment`.

## Verification

- `npx projen compile` succeeds (0 errors, 0 warnings)
- `npx jsii-pacmak -t go` generates `Env() *interfaces.ResourceEnvironment` matching the parent interface
- No impact on users with `aws-cdk-lib < 2.224.0` — they stay on the current release

## Backport

This fix is also applied to `kubectl-v33/main` (#2715) and `kubectl-v34/main` (#2714).

---

Fixes [aws/aws-cdk#37405](https://github.com/aws/aws-cdk/issues/37405)
Related: [aws/aws-cdk#36060](https://github.com/aws/aws-cdk/issues/36060)

### CODE REVIEW

File: API.md [hunk 1]
```diff
@@ -319,6 +333,25 @@ The runtimes compatible with this Layer.
...
 
+#### Constants <a name="Constants" id="Constants"></a>
+
+| **Name** | **Type** | **Description** |
+| --- | --- | --- |
+| <code><a href="#@aws-cdk/lambda-layer-kubectl-v35.KubectlV35Layer.property.PROPERTY_INJECTION_ID">PROPERTY_INJECTION_ID</a></code> | <code>string</code> | Uniquely identifies this class. |
+
+---
+
+##### `PROPERTY_INJECTION_ID`<sup>Required</sup> <a name="PROPERTY_INJECTION_ID" id="@aws-cdk/lambda-layer-kubectl-v35.KubectlV35Layer.property.PROPERTY_INJECTION_ID"></a>
```
Comment (leonmk-aws) [inline API.md:344]: Why do we need to add this now ?

Comment (aemada-aws) [reply API.md:344]: It is automatically generated

Comment (aemada-aws) [reply API.md:344]: My guess is before 2.224 property injections didn’t exist, so it shows up now.

**Review by leonmk-aws — APPROVED** [review]
